### PR TITLE
refactor: merge Submission and NewHeight events into one

### LINKED ISSUE #131: merge Submission and NewHeight events
currently we are emitting 2 different events with duplicate data on period submission:
1. [operator](https://github.com/leapdao/leap-contracts/blob/449bc4309073a5358a9be841058f5bd4b054bedf/contracts/PoaOperator.sol#L152-L157)
2. [bridge](https://github.com/leapdao/leap-contracts/blob/449bc4309073a5358a9be841058f5bd4b054bedf/contracts/Bridge.sol#L22)

## Deliveries
- combine these into 1
- adjust node event listener and make sure it passes integration tests

## Purpose Alignment
- cheaper period submission

## Bounty

gardener: @johannbarbie | 10%
worker: | 75%
reviewer: | 15%

### PR DESCRIPTION
**Pull request by troggy**
The change was merged at some point before. This reverts commit 32597d7126aa7c001801574de4146484570fd911.

Resolves #131

### CODE REVIEW

**Comment by johannbarbie** [comment]
how about this https://github.com/leapdao/leap-contracts/pull/205 😢

**Comment by troggy** [comment]
I can leave NewHeight instead of Submission and put all the stuff in it?

**Comment by troggy** [comment]
On a second thought, it is better to leave both events as they are. Otherwise the operator and bridge separation looks artificial: what's the point to calculate periodRoot in PoaOperator if it is used only in Bridge. @johannbarbie how about we leave it as it is, just closing #131 ?

**Comment by johannbarbie** [comment]
> @johannbarbie how about we leave it as it is, just closing #131 ?

best idea i think.

**Pull request closed without merging**
