### PR TITLE
feat: add migration to update contracts on the running network

### PR DESCRIPTION
**Pull request by troggy**
Can be used for contract update test scenarious like https://github.com/leapdao/leap-sandbox/issues/32

Usage:
1. checkout updated contract version
2. `yarn compile`
3. CONFIG=<path to network config> ./node_modules/.bin/truffle deploy --f 5

### CODE REVIEW

**Comment by troggy** [comment]
Needed for: https://github.com/leapdao/leap-sandbox/issues/32

This migration allows to upgrade contracts on the running network (config to which you supply by CONFIG env var).

What to test:
1. `yarn deploy` is not executing `5_update_contracts` step. We don't want this migration to be executed for regular deployments
2. `CONFIG=<path to network config> ./node_modules/.bin/truffle deploy --f 5` runs just one migration `5_update_contracts` and replaces implementations for existing contracts. If you want you can verify that implementation were indeed replaced by examining `.implementation()` calls on the plasma contract proxies, or just examining truffle deployment logs. You want to run this to upgrade contract implementions on the existing (local) network.

**Comment by troggy** [comment]
1. set up leap-sandbox to use local version of contracts (see README)
2. `yarn start` in leap-sandbox will start a network for that version of the contracts. Keep it running
3. Checkout other veriosn of the contracts locally or otherwise change and compile them
4. Execute `CONFIG=<path to network config> ./node_modules/.bin/truffle deploy --f 5`. The contracts on the running network should be upgraded

**Comment by johannbarbie** [comment]
this is what I get:

```
a1708:leap-contracts johba$ git checkout 9389ccd7ec53f36e54d2b28928782fe39eac03f0
HEAD is now at 9389ccd fix: BFT quorum for period CAS (#264)

a1708:leap-contracts johba$ CONFIG=local.js ./node_modules/.bin/truffle deploy --f 5

Compiling your contracts...
===========================
> Compiling ./contracts/PoaOperator.sol
> Compiling ./contracts/PosOperator.sol
> Compiling ./contracts/mocks/PoaOperatorMock.sol
> Compiling ./contracts/proxies/OperatorProxy.sol
[..]
> Artifacts written to /Users/johba/dev/leap-contracts/build/contracts
> Compiled successfully using:
   - solc: 0.5.2+commit.1df8f40c.Emscripten.clang

a1708:leap-contracts johba$
```

no contract upgrade 🤷‍♂

**Comment by troggy** [comment]
@johannbarbie you have to provide path to network config in `CONFIG` variable
image

**Comment by johannbarbie** [comment]
i've tried this one:
```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};
```
but it gives me: `Error: Cannot find module 'local.js'`

@troggy  what is the correct config to use?

**Comment by troggy** [comment]
@johannbarbie you need to provide a path to Leap Network config.. for local network it will be in `leap-contracts/build/nodeFiles/generatedConfig.json`

**Pull request merged**
